import { StyleSheet, Platform } from "react-native";
import { THEME } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    alignItems: "center",
    padding: 24,
    paddingTop: 40,
    paddingBottom: 32,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 16,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: THEME.colors.card,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: THEME.colors.primary,
    ...Platform.select({
      ios: {
        shadowColor: THEME.colors.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  avatarText: {
    fontSize: 40,
    fontWeight: "bold",
    color: THEME.colors.foreground,
  },
  statusBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: THEME.colors.background,
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: THEME.colors.background,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: THEME.colors.primary,
  },
  username: {
    fontSize: 24,
    fontWeight: "bold",
    color: THEME.colors.foreground,
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  email: {
    fontSize: 14,
    color: THEME.colors.mutedForeground,
    marginBottom: 12,
  },
  memberBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${THEME.colors.primary}15`,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  memberText: {
    fontSize: 12,
    color: THEME.colors.primary,
    fontWeight: "600",
  },
  statsContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: THEME.colors.foreground,
    marginBottom: 16,
    letterSpacing: 0.3,
  },
  statsGrid: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: THEME.colors.card,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  statIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: `${THEME.colors.primary}15`,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  statValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: THEME.colors.foreground,
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  statLabel: {
    fontSize: 11,
    color: THEME.colors.mutedForeground,
    textAlign: "center",
    fontWeight: "500",
  },
  infoCard: {
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: THEME.colors.card,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  infoHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    gap: 8,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: THEME.colors.foreground,
    letterSpacing: 0.3,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.border,
  },
  infoLabel: {
    fontSize: 14,
    color: THEME.colors.mutedForeground,
    fontWeight: "500",
  },
  infoValue: {
    fontSize: 14,
    color: THEME.colors.foreground,
    fontWeight: "600",
    maxWidth: "60%",
    textAlign: "right",
  },
  roleBadge: {
    backgroundColor: `${THEME.colors.secondary}20`,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  roleText: {
    fontSize: 12,
    color: THEME.colors.secondary,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  settingsCard: {
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: THEME.colors.card,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  settingItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.border,
  },
  settingLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingText: {
    fontSize: 16,
    color: THEME.colors.foreground,
    fontWeight: "500",
  },
  logoutButton: {
    marginHorizontal: 20,
    marginBottom: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${THEME.colors.destructive}15`,
    borderRadius: 16,
    padding: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: `${THEME.colors.destructive}30`,
  },
  logoutText: {
    fontSize: 16,
    color: THEME.colors.destructive,
    fontWeight: "700",
  },
  errorContainer: {
    margin: 20,
    padding: 32,
    alignItems: "center",
    backgroundColor: THEME.colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  errorText: {
    fontSize: 16,
    color: THEME.colors.destructive,
    marginVertical: 16,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: THEME.colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryText: {
    color: THEME.colors.primaryForeground,
    fontWeight: "700",
    fontSize: 14,
  },
});
