import { Dimensions, StyleSheet } from "react-native";
import { THEME } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {},
  pic: {
    height: Dimensions.get("window").height * 0.5 + 30,
    width: "100%",
  },
  informationContainer: {
    width: "100%",
    backgroundColor: "#fff",
    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
    marginTop: -24,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 32,
  },
  infos: {
    width: "85%",
    marginTop: -50,
    gap: 28,
  },
  goback: {
    position: "absolute",
    top: 54,
    left: 20,
    width: 44,
    height: 44,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
  },
  profilename: {
    color: THEME.COLORS.TEXT,
    fontSize: THEME.FONT_SIZE.LG,
    fontFamily: THEME.FONT_FAMILY.BOLD,
    letterSpacing: 0.5,
  },
  nameAndCourseContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: -10,
  },
  nameAndCourse: {
    flexDirection: "column",
    justifyContent: "center",
    gap: 4,
  },
  text: {
    color: THEME.COLORS.GRAY_TEXT,
    fontSize: THEME.FONT_SIZE.SM,
    fontFamily: THEME.FONT_FAMILY.REGULAR,
  },
  dmBtn: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: THEME.COLORS.BORDER,
  },
  locationContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: -10,
  },
  label: {
    color: THEME.COLORS.TEXT,
    fontSize: THEME.FONT_SIZE.MD,
    fontFamily: THEME.FONT_FAMILY.BOLD,
    letterSpacing: 0.5,
  },
  distance: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 4,
    paddingHorizontal: 10,
    height: 32,
    backgroundColor: "#F5F5F5",
  },
  distanceText: {
    fontFamily: THEME.FONT_FAMILY.BOLD,
    fontSize: THEME.FONT_SIZE.SM,
    color: THEME.COLORS.TEXT,
  },
  distanceIcon: {
    width: 14,
    height: 14,
  },
  simpleContainer: {
    justifyContent: "center",
    gap: 8,
    width: "100%",
  },
  readMore: {
    color: THEME.COLORS.TEXT,
    fontSize: THEME.FONT_SIZE.SM,
    fontFamily: THEME.FONT_FAMILY.BOLD,
    textDecorationLine: "underline",
  },
  interests: {
    flexWrap: "wrap",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  interest: {
    borderWidth: 1,
    borderColor: THEME.COLORS.BORDER,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 100,
    gap: 4,
  },
  interestChecked: {
    borderColor: THEME.COLORS.TEXT,
    backgroundColor: THEME.COLORS.TEXT,
  },
  interestText: {
    color: THEME.COLORS.TEXT,
    fontSize: THEME.FONT_SIZE.SM,
    fontFamily: THEME.FONT_FAMILY.REGULAR,
    letterSpacing: 0.5,
  },
  interestTextChecked: {
    color: THEME.COLORS.WHITE_TEXT,
  },
  gallery: {
    marginTop: 8,
    height: Dimensions.get("window").height * 0.425,
    flexDirection: "column",
    gap: 8,
  },
  galleryRow: {
    justifyContent: "space-between",
    flexDirection: "row",
    gap: 8,
  },
  galleryPic: {
    borderRadius: 4,
    flex: 1,
  },
});
